### ISSUE TITLE
Requiring com.google.* Optional as return type for getWebSecurityConfiguation

### ISSUE THREAD

**Issue by rcchen** [palantir/dropwizard-web-security#18]
I have to do this when I'm working in a code base that uses Java 8 optionals

```
@Override
public com.google.common.base.Optional<WebSecurityConfiguration> getWebSecurityConfiguration() {
        return this.webSecurity;
}
```

:cry:

**Comment by jmcampanini** [comment]
yea that's no fun. will look into if there's a way to not have Optional be there, without imposing too much overhead for people who want JUST the default settings. the code change is clean/easy, just want to think through it a bit.

**Comment by derekcicerone-zz** [comment]
Can we just take the Java 8 dependency? We should be consistent across apps and Dropwizard is going Java 8-only next anyways.

**Comment by jmcampanini** [comment]
related to java7 vs java8 in #22

**Comment by jmcampanini** [comment]
we're going to go with java7 for now, which means using the guava `Optional`. closing.
