### ISSUE TITLE
ensure configuration interface uses consistent naming pattern

### ISSUE THREAD

**Issue by jmcampanini** [palantir/dropwizard-web-security#21]
we want to make sure we're consistent in what we're naming our interfaces that application `Configuration`s are implementing.

in this case, we're using the `*Configurable` pattern. in others, we're using `*ConfigurationProvider`.

**Comment by qinfchen** [comment]
+1 on `*Configurable` for shorter and simpler name. The problem with `*ConfigurationProvider` is that when multiple bundles are added to an app, the app configuration needs to implement multiple `*ConfigurationProvider`s and it becomes harder to read.

**Comment by jmcampanini** [comment]
i also believe the `*Provider` naming convention is a bit overloaded, especially if you end up adding some sort of DI framework.

**Comment by qinfchen** [comment]
Dropwizard's native bundle also uses the `*Configurable` Pattern, see 
https://github.com/dropwizard/dropwizard/blob/d268137305915804a79d5cf2e42e6e03da44df10/dropwizard-views/src/main/java/io/dropwizard/views/ViewConfigurable.java

**Comment by jmcampanini** [comment]
sticking to `*Configurable`
