### ISSUE TITLE
Making WebSecurityConfiguration Optional again

### ISSUE THREAD

**Issue by qinfchen** [palantir/dropwizard-web-security#40]
The 0.11.0 release removes Optional<> from the web security configuration. Although the new style is pretty neat, but we are forcing the consuming app to use this same style vs using constructor. With the new style, the `WebSecurityConfiguration` is guaranteed to be not null, but we still can't avoid `CheckForNull` precondition checks.

Note that without the use of Optional, you are kind of forced to use the new style. With Optional, you can use both styles. So can we add the Optional back and let the consuming app choose which style to use?

new style:

```
    @Valid
    @JsonProperty("webSecurity")
    private WebSecurityConfiguration webSecurityConfiguration = WebSecurityConfiguration.DEFAULT;

    @Override
    public WebSecurityConfiguration getWebSecurityConfiguration() {
        return this.webSecurityConfiguration;
    }
```

constructor:

```
    @Valid
    private final Optional<WebSecurityConfiguration> webSecurityConfiguration;

    @JsonCreator
    public ExampleApp(@JsonProperty("webSecurity") Optional<WebSecurityConfiguration> webSecurityConfiguration) {
        this.webSecurityConfiguration = webSecurityConfiguration;
    }
```

**Comment by jmcampanini** [comment]
there's nothing stopping the consuming application from using `Optional` for their constructor. if anything we should be removing those annotations from our `WebSecurityConfigurable`.

nothing stops them from using a constructor and doing the following:

``` java
@JsonCreator
    public ExampleApp(@JsonProperty("webSecurity") Optional<WebSecurityConfiguration> webSecurityConfigurationOptional) {
        this.webSecurityConfiguration = webSecurityConfigurationOptional.or(WebSecurityConfiguration.DEFAULT);
    }
```

the way it's setup now is saying "the config must be able to return a `WebSecurityConfiguration` object. it's not saying how it needs to get one.

i think that makes this a non-issue.

**Comment by qinfchen** [comment]
ahh. good point. Closing this.
