### ISSUE TITLE
allow inline styles

### ISSUE THREAD

**Issue by jmcampanini** [palantir/dropwizard-web-security#52]
the current default for ContentSecurityPolicy is `default-src 'self'`

would like to change this to allow inline CSS for dynamic elements. the change would be to:

```
default-src 'self'; style-src 'self' 'unsafe-inline'
```

@adidahiya will this be sufficient for your needs?

// tagging for SA @akroy @qinfchen @tomshen

**Comment by adidahiya** [comment]
:+1: sgtm

**Comment by hellochar** [comment]
:+1: we're currently overriding the the csp in our product to allow for this
