### ISSUE TITLE
Inconsistency between default X-Frame-Options and Content-Security-Policy

### ISSUE THREAD

**Issue by stuartgunter** [palantir/dropwizard-web-security#62]
Hi

I was going to submit this as a PR, but I thought it’d be easier to just note this as an issue because I haven’t signed the CLA.

There appears to be inconsistency between the default values for `Content-Security-Policy` and `X-Frame-Options`. I'm not sure if this will cause any problems in how browsers interpret it (I don't think it should because of https://www.w3.org/TR/CSP2/#frame-ancestors-and-frame-options). However, it seems likely to cause developer confusion or live site issues when browsers fully remove support for `X-Frame-Options` (see https://www.chromestatus.com/features/6450843930853376) and are left allowing framing everywhere due to the lack of a `frame-ancestors 'self';` directive.

Is this something you've thought about?

Hope this is helpful.
Stuart

PS: Great work on this library. I started creating the same thing on my commute this morning, but then when I came back online I noticed you’d already done it. Nice one!

PPS: I appreciate you likely have a legal department that has instructed the use of a CLA, but without a seamless online process for doing this it is likely to constrain open contribution to the library. For example, I would have happily submitted this as a code change to save you the work if it had been easier. (Of course, you’re still free to decide that it’s not in line with where you want to take the library). I hope this is received as constructive feedback.

**Comment by jmcampanini** [comment]
firstly, wanted to apologize for the delay in responding.

secondly, i believe we may have (or soon will) a better CLA workflow, but haven't added it to this project yet. I'm investigating and will update this thread with any updates.

---

for your issue in particular, if i understand it correctly, the idea is to add `frame-ancestors 'self';` to the CSP to do the following:
1. make the CSP policies consistent with the Frame Options in the current world
2. in the future, when Frame Options goes away, we maintain consistent behavior

is that correct?

---

lastly, glad to hear you find this bundle useful :)

**Comment by jmcampanini** [comment]
following up on the CLA workflow, there's a simple, streamlined version where we're using HelloSign to get the CLAs signed. I'll update the READMEs.

EDIT: here's a link to update the CLA process: https://github.com/palantir/dropwizard-web-security/pull/65 - merged!

**Comment by stuartgunter** [comment]
Hi, thanks for responding.

Yes, you've summarised my comments correctly. My main concern is one of consistency. I think the default policy in both `X-Frame-Options` and `Content-Security-Policy` should be consistent with each other. What the values are set to is potentially open for debate - e.g. by default, I'm guessing most sites do not need framing at all and can therefore default to `DENY` and 'frame-ancestors: 'none'` - but I'm going on a bit of a tangent from the point now :-)
