### ISSUE TITLE
Update 3rd party module list

### ISSUE THREAD

**Issue by mnazbro** [palantir/dropwizard-web-security#69]
This list (http://modules.dropwizard.io/thirdparty/) looks out-of-date. It doesn't mention that dropwizard-web-security on Dropwizard 1.0.

**Comment by qinfchen** [comment]
this apply to other bundles as well..

**Comment by qinfchen** [comment]
https://github.com/dropwizard/modules.dropwizard.io/pull/53

**Comment by jmcampanini** [comment]
should be updated. closing.
